# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b60f595dbb778a36e6af50956a2d10d241a9a8eae925063fcaef4377dbf69be7a54dbe5742cad2084104b3d38d1bb3d94fe2eda73759b2c9844f17258c599b38

test:
  secret_key_base: 59f8ac8e172272874800d77f75882e17f998dc973a0b793e9d42404606c4879d47bc6ab666c47072dd39684c01281d914a6f83b25538cc9d96b008c8409581f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
